
import "@/app/globals.css"

// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/dash/Header';
import HeaderMobile from '@/components/dash/Header-mobile';
import MarginWidthWrapper from '@/components/dash/Margin-with-wrapper';
import PageWrapper from '@/components/dash/Page-wrapper';
import SideNav from '@/components/dash/Side-nav';
import Page from "./Page_content";


// export const metadata: Metadata = {
//   title: 'Side Nav w/ Sub Menu',
//   description: 'Generated by create next app',
// };

const page = () => {

  return (
    
      
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header />
              <HeaderMobile />
              <PageWrapper>
              <Page />
              </PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      
    
  );
}
export default page